version: "3.8"

services:
  coordinator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: coordinator
    command: ./algoritmo_distribuido
    networks:
      - distnet
    cap_add:
      - NET_ADMIN

  worker1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: worker1
    command: ./algoritmo_distribuido worker
    networks:
      - distnet
    cap_add:
      - NET_ADMIN
    environment:
      - WORKER_ID=1

  worker2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: worker2
    command: ./algoritmo_distribuido worker
    networks:
      - distnet
    cap_add:
      - NET_ADMIN
    environment:
      - WORKER_ID=2

  worker3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: worker3
    command: ./algoritmo_distribuido worker
    networks:
      - distnet
    cap_add:
      - NET_ADMIN
    environment:
      - WORKER_ID=3

  worker4:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: worker4
    command: ./algoritmo_distribuido worker
    networks:
      - distnet
    cap_add:
      - NET_ADMIN
    environment:
      - WORKER_ID=4

networks:
  distnet:
    name: distnet
    driver: bridge
