version: "3.8"

services:

  coordinator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ./algoritmo_distribuido
    networks:
      distnet:
        ipv4_address: 172.28.0.10

  worker1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ./algoritmo_distribuido worker
    depends_on:
      - coordinator
    networks:
      distnet:
        ipv4_address: 172.28.0.11

  worker2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ./algoritmo_distribuido worker
    depends_on:
      - coordinator
    networks:
      distnet:
        ipv4_address: 172.28.0.12

  worker3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ./algoritmo_distribuido worker
    depends_on:
      - coordinator
    networks:
      distnet:
        ipv4_address: 172.28.0.13

  worker4:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ./algoritmo_distribuido worker
    depends_on:
      - coordinator
    networks:
      distnet:
        ipv4_address: 172.28.0.14

networks:
  distnet:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.28.0.0/16
